_BASE_: ../DAQ_Online_R50.yaml
MODEL:
  BACKBONE:
    NAME: "D2VitAdapterDinoV2"
  VIT_ADAPTER:
    FINETUNE: False
    NAME: 'vitl'
    VIT_WEIGHT: './weights/DINOv2/dinov2_vitl14_pretrain_.pth'
    FREEZE_VIT: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_FORMER:
    NUM_OBJECT_QUERIES: 200
  VIDEO_HEAD:
    NUM_SLOTS: 5
    NUM_NEW_INS: 200

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (66000,)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000

DATALOADER:
  NUM_WORKERS: 4

INPUT:
  SAMPLING_FRAME_NUM: 5
  SAMPLING_FRAME_RANGE: 2
  SAMPLING_FRAME_SHUFFLE: False
  USING_FRAME_NUM: [ 2, 5 ]
  STEPS: [ 10000 ]

TEST:
  EVAL_PERIOD: 0

OUTPUT_DIR: './output_DAQ_Online_ViTL_VIPSeg_90k'